"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";

type Catalog={controls:any[];clients:any[];projects:any[];studies:any[];mirofish:any};
export default function Dashboard(){
 const [data,setData]=useState<Catalog|null>(null); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
 const [clientId,setClientId]=useState(""); const [projectId,setProjectId]=useState(""); const [title,setTitle]=useState(""); const [question,setQuestion]=useState("¿Dónde existe valor que hoy no está circulando, qué impide que se realice y qué conexión podría liberarlo de forma recurrente?");
 async function load(){const r=await fetch("/api/bootstrap",{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error||"bootstrap_failed");setData(j)}
 useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 const root=useMemo(()=>data?.controls?.find(c=>c.is_root)||data?.controls?.[0], [data]);
 const clientProjects=useMemo(()=>!data?[]:data.projects.filter(p=>!clientId||p.client_id===clientId),[data,clientId]);
 async function create(e:React.FormEvent){e.preventDefault();if(!root)return;setBusy(true);setError("");const r=await fetch("/api/studies",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({controlId:root.id,clientId:clientId||null,projectId:projectId||null,title,question,studyType:"value_discovery",questionLevel:"root"})});const j=await r.json();if(!r.ok){setError(j.error||"create_failed");setBusy(false);return;}location.href=`/study/${j.study.id}`;}
 if(!data)return <div className="panel">{error?<div className="error">{error}</div>:"Cargando datos reales de Control Central…"}</div>;
 return <div className="stack">
  <section className="panel stack"><div className="eyebrow">Máquina consultiva · separada de Control Central</div><h1>Encontrar valor antes de construir.</h1><p className="lead">LINK STUDY toma contexto real de cada negocio, congela un snapshot verificable y permite a ChatGPT o MiroFish estudiar valor latente, fricción, conexiones y escenarios sin escribir sobre la operación.</p><div className="row"><span className="pill"><span className="dot good"/>Supabase central conectado</span><span className="pill"><span className={`dot ${data.mirofish?.reachable?"good":data.mirofish?.configured?"bad":"warn"}`}/>{data.mirofish?.reachable?"MiroFish conectado":data.mirofish?.configured?"MiroFish sin respuesta":"MiroFish no configurado"}</span></div></section>
  <section className="grid cols-3"><div className="panel"><div className="eyebrow">Negocios reales</div><div className="metric">{data.clients.length}</div><div className="muted small">clientes disponibles para contexto</div></div><div className="panel"><div className="eyebrow">Proyectos reales</div><div className="metric">{data.projects.length}</div><div className="muted small">registros en Control Central</div></div><div className="panel"><div className="eyebrow">Estudios</div><div className="metric">{data.studies.length}</div><div className="muted small">experimentos persistentes</div></div></section>
  <section className="grid cols-2">
   <form className="panel stack" onSubmit={create}><div className="spread"><div><div className="eyebrow">Nuevo estudio</div><h2>Pregunta elevada</h2></div><span className="badge">No altera operación</span></div><div className="field"><label>Negocio / cliente</label><select className="select" value={clientId} onChange={e=>{setClientId(e.target.value);setProjectId("")}}><option value="">Contexto raíz / proyecto independiente</option>{data.clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="field"><label>Proyecto específico (opcional)</label><select className="select" value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">Todo el contexto del negocio</option>{clientProjects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><div className="field"><label>Título</label><input className="input" value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ej. Descubrimiento de valor Hotel Experience" /></div><div className="field"><label>Pregunta madre</label><textarea className="textarea" value={question} onChange={e=>setQuestion(e.target.value)} /></div>{error&&<div className="error small">{error}</div>}<button className="btn primary" disabled={busy||title.trim().length<3||question.trim().length<10}>{busy?"Creando…":"Crear estudio real"}</button></form>
   <div className="panel stack"><div className="eyebrow">Contextos disponibles</div><h2>Lo que realmente existe hoy</h2>{data.clients.length===0?<div className="empty">Control Central todavía no contiene clientes disponibles.</div>:<div className="cards">{data.clients.map(c=>{const count=data.projects.filter(p=>p.client_id===c.id).length;return <div className="card" key={c.id}><div className="spread"><strong>{c.name}</strong><span className="badge code">{c.short_code||c.slug}</span></div><div className="muted small" style={{marginTop:8}}>{count} proyecto{count===1?"":"s"} · status {c.status}</div></div>})}</div>}<div className="divider"/><div className="small muted">La lista viene de Supabase en vivo. Si un negocio aún no está registrado en Control Central, LINK STUDY no lo inventa.</div></div>
  </section>
  <section className="panel stack"><div className="spread"><div><div className="eyebrow">Biblioteca</div><h2>Estudios persistentes</h2></div></div>{data.studies.length===0?<div className="empty">Todavía no hay estudios.</div>:<div className="cards">{data.studies.map(s=><Link className="card" href={`/study/${s.id}`} key={s.id}><div className="spread"><strong>{s.title}</strong><span className="badge code">{s.study_code}</span></div><p className="small muted">{s.question}</p><div className="row"><span className="badge">{s.study_type}</span><span className="badge">{s.status}</span></div></Link>)}</div>}</section>
 </div>
}
