"use client";
import { useEffect,useMemo,useState } from "react";
import Link from "next/link";

export default function StudyView({id}:{id:string}){
 const [data,setData]=useState<any>(null);const [error,setError]=useState("");const [busy,setBusy]=useState("");
 async function load(){const r=await fetch(`/api/studies/${id}`,{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error||"study_load_failed");setData(j)}
 useEffect(()=>{load().catch(e=>setError(e.message))},[id]);
 const latest=useMemo(()=>data?.snapshots?.[0]||null,[data]);
 async function post(path:string,label:string){setBusy(label);setError("");const r=await fetch(path,{method:"POST",headers:{"content-type":"application/json"},body:"{}"});const j=await r.json().catch(()=>({}));if(!r.ok){setError(j.error||`${label}_failed`);setBusy("");return;}await load();setBusy("");}
 if(!data)return <div className="panel">{error?<div className="error">{error}</div>:"Cargando estudio…"}</div>;
 const s=data.study;const miro=data.mirofish;
 return <div className="stack">
  <div className="topbar"><Link className="btn" href="/">← Estudios</Link><span className="pill code">{s.study_code}</span></div>
  <section className="panel stack"><div className="spread"><div><div className="eyebrow">{s.study_type} · {s.question_level}</div><h1 style={{fontSize:"clamp(26px,4vw,46px)"}}>{s.title}</h1></div><span className="badge">{s.status}</span></div><p className="lead">{s.question}</p><div className="row"><button className="btn primary" onClick={()=>post(`/api/studies/${id}/snapshot`,"snapshot")} disabled={!!busy}>{busy==="snapshot"?"Capturando…":latest?"Actualizar snapshot real":"Construir snapshot real"}</button>{miro?.reachable&&<button className="btn" onClick={()=>post(`/api/studies/${id}/mirofish`,"mirofish")} disabled={!!busy||!latest}>{busy==="mirofish"?"Enviando…":"Enviar a MiroFish"}</button>}<span className="pill"><span className={`dot ${miro?.reachable?"good":miro?.configured?"bad":"warn"}`}/>{miro?.reachable?"MiroFish listo":miro?.configured?"MiroFish sin respuesta":"MiroFish no configurado"}</span></div>{error&&<div className="error small">{error}</div>}</section>
  <section className="grid cols-3"><div className="panel"><div className="eyebrow">Cobertura contextual</div><div className="metric">{latest?.coverage?.percentage??0}%</div><div className="bar"><span style={{width:`${latest?.coverage?.percentage??0}%`}}/></div><div className="muted small" style={{marginTop:8}}>{latest?`snapshot v${latest.snapshot_version}`:"sin snapshot"}</div></div><div className="panel"><div className="eyebrow">Hallazgos</div><div className="metric">{data.findings.length}</div><div className="muted small">clasificados por verdad</div></div><div className="panel"><div className="eyebrow">Oportunidades</div><div className="metric">{data.opportunities.length}</div><div className="muted small">valor medido y persistente</div></div></section>
  <section className="grid cols-2">
   <div className="panel stack"><div className="eyebrow">Contexto congelado</div><h2>Fuentes reales</h2>{!latest?<div className="empty">Crea un snapshot antes de analizar o simular.</div>:<>{Object.entries(latest.source_counts||{}).map(([k,v])=><div className="spread small" key={k}><span className="code">{k}</span><strong>{String(v)}</strong></div>)}<div className="divider"/><div className="tiny muted code">digest {latest.source_digest}</div></>}</div>
   <div className="panel stack"><div className="eyebrow">Motor experimental</div><h2>MiroFish</h2>{!miro?.configured?<div className="empty">Configura <span className="code">MIROFISH_API_URL</span> para habilitar simulación real.</div>:!miro?.reachable?<div className="error small">El servidor configurado no responde a /health.</div>:<div className="success small">MiroFish responde correctamente. El botón de envío está habilitado sólo porque la comprobación fue real.</div>}{data.runs.map((r:any)=><div className="card" key={r.id}><div className="spread"><strong>{r.engine}</strong><span className="badge">{r.status}</span></div><div className="small muted" style={{marginTop:8}}>etapa: <span className="code">{r.response_payload?.stage||"queued"}</span></div>{r.engine==="mirofish"&&r.status==="running"&&<button className="btn" style={{marginTop:10}} onClick={()=>post(`/api/runs/${r.id}/sync`,`sync-${r.id}`)} disabled={!!busy}>{busy===`sync-${r.id}`?"Sincronizando…":"Sincronizar MiroFish"}</button>}{r.error&&<div className="error small" style={{marginTop:8}}>{r.error}</div>}</div>)}</div>
  </section>
  <section className="grid cols-2"><div className="panel stack"><div className="eyebrow">Análisis</div><h2>Hallazgos</h2>{data.findings.length===0?<div className="empty">ChatGPT puede guardar hallazgos por MCP después de revisar el snapshot.</div>:data.findings.map((f:any)=><div className="card" key={f.id}><div className="spread"><strong>{f.title}</strong><span className={`badge ${f.truth_class}`}>{f.truth_class}</span></div><p className="small muted">{f.body}</p>{f.confidence!=null&&<div className="tiny">confianza {Math.round(Number(f.confidence)*100)}%</div>}</div>)}</div><div className="panel stack"><div className="eyebrow">Valor</div><h2>Oportunidades</h2>{data.opportunities.length===0?<div className="empty">Las oportunidades se crean con evidencia y ocho dimensiones de valoración.</div>:data.opportunities.map((o:any)=><div className="card" key={o.id}><div className="spread"><strong>{o.title}</strong><span className="badge">{o.opportunity_score??"—"}/100</span></div><p className="small muted">{o.description||"Sin descripción"}</p><div className="bar"><span style={{width:`${o.opportunity_score||0}%`}}/></div></div>)}</div></section>
 </div>
}
